### ISSUE TITLE
Contingency Plan DLC 適用時に翻訳済みの日本語が表示されない

### ISSUE THREAD

**Issue by nsk4762jp** [nsk4762jp/Invisible-Inc-Japanese#3]
Contingency Plan を導入した後、 翻訳済みの日本語が表示されない箇所があった。
とりあえず確認できたのは下記のとおり。

・ 設定画面のキー割り当て
・ 日付変更時のストーリー進捗状況メッセージ
・ ミッションの説明上段および追加情報

**Comment by LNK02** [comment]
翻訳おつかれさまです。そしてありがとうございます。
ところで、誤訳と思わしき箇所を見つけたので報告させていただいきます。
ホロサーキットオーバーローダーの説明欄の
"This effect triggers after the agent becomes cloaked for any reason"の訳ですが、
「エージェントを無条件に透明化します」から
「エージェントがなんらかの理由で透明になると発動します」
に修正お願いします。

**Comment by nsk4762jp** [comment]
あ、指摘ありがとうございます。
「エージェントが透明化すると発動します。」に直します。

**Comment by nsk4762jp** [comment]
他の言語パックだとどうなるか確認した。

・ ロシア語 → 同じ現象
・ 中国語 → 同じ現象

念のため DLC を有効化した状態で strings.pot ファイルを再生成し、それを翻訳してみた結果もダメだった。
DLC の問題っぽい？

**Comment by nsk4762jp** [comment]
http://forums.kleientertainment.com/topic/59019-language-packs-not-working-after-contingency-plans-release/

他の言語パックでも同様の現象が起きている模様。

**Comment by nsk4762jp** [comment]
2015/11/21 アップデートにより問題解決。 Issue はクローズとする。
